# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jatt < Formula
  desc ""
  homepage "https://github.com/devmegablaster/jatt"
  version "0.3"

  on_macos do
    on_intel do
      url "https://github.com/devmegablaster/jatt/releases/download/v0.3/jatt_Darwin_x86_64.tar.gz"
      sha256 "21ace809b2636164f76cbee69452b266ad6208102aa8d9558ad8cee80078716d"

      def install
        bin.install "jatt"
      end
    end
    on_arm do
      url "https://github.com/devmegablaster/jatt/releases/download/v0.3/jatt_Darwin_arm64.tar.gz"
      sha256 "14e4c5eef08ec103e5fc9c6ee86b9a742e7535df9940883908ca9ca8e18db154"

      def install
        bin.install "jatt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devmegablaster/jatt/releases/download/v0.3/jatt_Linux_x86_64.tar.gz"
        sha256 "d16b4e6f4def6b32581f57dbb112ef85e02bc0d130dba5d5c5095f49567ab78f"

        def install
          bin.install "jatt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devmegablaster/jatt/releases/download/v0.3/jatt_Linux_arm64.tar.gz"
        sha256 "1ce7b15ae0104851fb345109932b318fb7cf88f846b086a8871800d023152bb8"

        def install
          bin.install "jatt"
        end
      end
    end
  end
end
