# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jatt < Formula
  desc ""
  homepage "https://github.com/devmegablaster/jatt"
  version "0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devmegablaster/jatt/releases/download/v0.12/jatt_Darwin_x86_64.tar.gz"
      sha256 "471897a8a49076bf30fa030306d4dab5ef7ed0bc73b996b7b44290cdbefe83bb"

      def install
        bin.install "jatt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devmegablaster/jatt/releases/download/v0.12/jatt_Darwin_arm64.tar.gz"
      sha256 "674fc49a26fd72f2818f090a418c49e0f306f05c30569da6fca1333e4af2a563"

      def install
        bin.install "jatt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devmegablaster/jatt/releases/download/v0.12/jatt_Linux_x86_64.tar.gz"
        sha256 "981e4806a06a38f8dbd42889596a2fa518ce4730a3b5f6a48e6ee6c8033b91d1"

        def install
          bin.install "jatt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devmegablaster/jatt/releases/download/v0.12/jatt_Linux_arm64.tar.gz"
        sha256 "92bb028b436193cbcac366fbd5fee88059a96215e2550203175fbb9bccea0f59"

        def install
          bin.install "jatt"
        end
      end
    end
  end
end
