# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jatt < Formula
  desc ""
  homepage "https://github.com/devmegablaster/jatt"
  version "0.5"

  on_macos do
    on_intel do
      url "https://github.com/devmegablaster/jatt/releases/download/v0.5/jatt_Darwin_x86_64.tar.gz"
      sha256 "c3318a41c2377c0c348abadf7d29a6503e80947236b928bea232f6318e87bdd9"

      def install
        bin.install "jatt"
      end
    end
    on_arm do
      url "https://github.com/devmegablaster/jatt/releases/download/v0.5/jatt_Darwin_arm64.tar.gz"
      sha256 "6c1c59099b888680ae2ad6089ae75bee14152e7d9508dcc072a3e1f768aba017"

      def install
        bin.install "jatt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devmegablaster/jatt/releases/download/v0.5/jatt_Linux_x86_64.tar.gz"
        sha256 "aabdac832566180f60c14fcf595c3523da1e9b3a8d80f8a541d6369005c90fa1"

        def install
          bin.install "jatt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devmegablaster/jatt/releases/download/v0.5/jatt_Linux_arm64.tar.gz"
        sha256 "a8ca07f30f1268c653672ddffe09b12d8ebe03b656dc6a81df9e4c6a9f5c23a7"

        def install
          bin.install "jatt"
        end
      end
    end
  end
end
