# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pswt < Formula
  desc ""
  homepage "https://github.com/devmegablaster/pastewut-cli/"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devmegablaster/pastewut-cli/releases/download/v1.1.2/pastewut-cli_1.1.2_darwin_arm64.tar.gz"
      sha256 "9366cff6b88a46755000f7d84571a90856e0441e6125ce5788d706223990825e"

      def install
        bin.install "pswt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devmegablaster/pastewut-cli/releases/download/v1.1.2/pastewut-cli_1.1.2_darwin_amd64.tar.gz"
      sha256 "2be202845155898eabff0769123dcdce3b0136948a2cb28da83227c191077fc4"

      def install
        bin.install "pswt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/devmegablaster/pastewut-cli/releases/download/v1.1.2/pastewut-cli_1.1.2_linux_amd64.tar.gz"
      sha256 "a44b2a5176cb731ca569d7d9ff87d8b2a749c87329f1645f99ef9e52d7701dc8"

      def install
        bin.install "pswt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devmegablaster/pastewut-cli/releases/download/v1.1.2/pastewut-cli_1.1.2_linux_arm64.tar.gz"
      sha256 "0a49ef86bf178f69a3061b446337fe26e2306c5294e79843b4ee71a1f7014af9"

      def install
        bin.install "pswt"
      end
    end
  end
end
