# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pswt < Formula
  desc ""
  homepage "https://github.com/devmegablaster/pastewut-cli/"
  version "1.0.2"

  on_macos do
    url "https://github.com/devmegablaster/pastewut-cli/releases/download/v1.0.2/pastewut-cli_1.0.2_darwin_all.tar.gz"
    sha256 "52c8326896c27ca91d45c815df6c229ddbd5c07891672bacd8f678b462a2c0ef"

    def install
      bin.install "pastewut-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devmegablaster/pastewut-cli/releases/download/v1.0.2/pastewut-cli_1.0.2_linux_arm64.tar.gz"
      sha256 "3e3889e484fa4bc5fa0513065f56f69c84b0a48e93e0d6e323478d3977996303"

      def install
        bin.install "pswt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devmegablaster/pastewut-cli/releases/download/v1.0.2/pastewut-cli_1.0.2_linux_amd64.tar.gz"
      sha256 "691036b5ed7f240ed3e031c80596b0cb41d36beb1bb552a58b4c4446ba908598"

      def install
        bin.install "pswt"
      end
    end
  end
end
